### ISSUE TITLE
Support for -iquote

### ISSUE THREAD

**Issue by itollefsen** [randomphrase/ede-compdb#11]
The "-iquote" option means search this include path only for headers included with quotes, not for headers included with angle brackets.

I added it locally along with the others in parse-command-line(...), and that seemed to do the trick.

**Comment by randomphrase** [comment]
As per the notice in the readme, this project is not being maintained because it has been merged into cedet proper. However if you get the latest cedet you will see that support for `-iquote` was already added a few months back.

**Comment by itollefsen** [comment]
Ah, sorry, didn't notice that. I need to update my cedet.
