### ISSUE TITLE
Unable to find include files

### ISSUE THREAD

**Issue by zhongweiy** [randomphrase/ede-compdb#5]
Hi, there,
I try to use ede-compdb on project ne10(https://github.com/projectNe10/Ne10) with following configuration:
``` 
(require 'ede-compdb)
(ede-compdb-project "ne10"
                    :file "~/ne10/CMakeLists.txt"
                    :compdb-file "~/ne10/build/compile_commands.json")
```
under Emacs 24.4.1. But emacs can't find including file in project itself. E.g. for the file https://github.com/projectNe10/Ne10/blob/master/modules/dsp/NE10_fft.c, it can't find:
```
#include "NE10_types.h"
#include "NE10_macros.h"
```
The related entry in my compile_commands.json is:
```
{
  "directory": "/home/ne10/build/modules",
  "command": "/home/webrtc/src/third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc  -DENABLE_NE10_FIR_DECIMATE_FLOAT_NEON -DENABLE_NE10_FIR_FLOAT_NEON -DENABLE_NE10_FIR_INTERPOLATE_FLOAT_NEON -DENABLE_NE10_FIR_LATTICE_FLOAT_NEON -DENABLE_NE10_FIR_SPARSE_FLOAT_NEON -DENABLE_NE10_IIR_LATTICE_FLOAT_NEON -DENABLE_NE10_IMG_ROTATE_RGBA_NEON -DENABLE_NE10_PHYSICS_APPLY_IMPULSE_VEC2F_NEON -DENABLE_NE10_PHYSICS_COMPUTE_AABB_VEC2F_NEON -DENABLE_NE10_PHYSICS_RELATIVE_V_VEC2F_NEON -DNE10_ANDROID_DEMO -DNE10_ENABLE_DSP -DNE10_ENABLE_HF -DNE10_ENABLE_IMGPROC -DNE10_ENABLE_MATH -DNE10_ENABLE_PHYSICS  -O2 -DNDEBUG --sysroot=/home/third_party/android_tools/ndk/platforms/android-21/arch-arm/ -pie -mthumb-interwork -mthumb -march=armv7-a -mfloat-abi=hard -mfpu=vfp3 -Wl,--no-warn-mismatch -I/home/ne10/inc -I/home/ne10/common    -o CMakeFiles/NE10.dir/dsp/NE10_fft.c.o   -c /home/ne10/modules/dsp/NE10_fft.c",
  "file": "/home/ne10/modules/dsp/NE10_fft.c"
},
```

How can I solve this? 

Another question is does ede-compdb support --sysroot option now? The ne10 project is cross-compiled, but I find emacs just jump to native system include file.

Thanks!

**Comment by randomphrase** [comment]
Thanks for the detailed bug report. What is the output of `M-x semantic-decoration-all-include-summary` ? Those include files should be found in the `.../inc` directory, correct? Is that directory listed in the include path?

**Comment by zhongweiy** [comment]
Here is the output of M-x semantic-decoration-all-include-summary:
```
Include Summary for File: /home/ne10/modules/dsp/NE10_fft.c

This file contains 7 tags, 3 of which are includes.
   Unknown Includes:  2
   Unparsed Includes: 0
   Parsed Includes:   1

Include Path Summary:


  This file's system include path is:
    /usr/include
    /usr/lib/gcc/x86_64-linux-gnu/4.8/include/
    /usr/local/include/
    /usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed/
    /usr/include/x86_64-linux-gnu/
    /usr/include/

All unknown includes:
  NE10_macros.h
  NE10_types.h

Summary of all includes needed by NE10_fft.c
  NE10_fft.c :	7 tags, 3 are includes. 
  NE10_fft.h :	31 tags, 5 are includes. 
  NE10_fft_common_varibles.h :	8 tags, 1 are includes. 
  NE10_fft_cplx_ops.h :	11 tags, 1 are includes. 
  NE10_fft_bfly.h :	10 tags, 3 are includes. 
  NE10_fft_debug_macro.h :	9 tags, 1 are includes. 

```
And yes, the unknown includes should be found in ```/home/ne10/inc``` directory. But it is not listed in above including path summary.

**Comment by randomphrase** [comment]
OK can you send me the output of `M-: (oref ede-object compilation)`?

**Comment by randomphrase** [comment]
Also, please feel free to raise a separate issue for `--sysroot` support.

**Comment by zhongweiy** [comment]
Sorry, but ```M-: (oref ede-object compilation)``` gives me:
```
Debugger entered--Lisp error: (wrong-type-argument (or eieio-object-p class-p) nil)
  signal(wrong-type-argument ((or eieio-object-p class-p) nil))
  eieio-oref(nil compilation)
  (oref ede-object compilation)
  eval((oref ede-object compilation) nil)
  eval-expression((oref ede-object compilation) nil)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```
My startup configuration is:
```
(semantic-mode t)
(global-ede-mode t)
(require 'ede-compdb)
(ede-compdb-project "ne10"
                    :file "~/ne10/CMakeLists.txt"
                    :compdb-file "~/ne10/build/compile_commands.json")
```
Did I miss something here?

**Comment by randomphrase** [comment]
You need to use `(ede-add-project-to-global-list (ede-compdb-project ...))`. I can see how the documentation is unclear on this - I will fix.

**Comment by zhongweiy** [comment]
Thanks, it works now!

**Comment by zhongweiy** [comment]
I find it breaks again on one ninja project. My configuration is:
```
(ede-add-project-to-global-list
 (ede-ninja-project "webrtc"
                     :file "~/webrtc/src/webrtc/webrtc.gyp"
                     :compdb-file "~/webrtc/src/out/Release/build.ninja"))
```
```M-x semantic-decoration-all-include-summary``` returns:
```
Include Summary for File: /home/zhongwei/webrtc/src/webrtc/modules/audio_processing/gain_control_impl.cc

This file contains 6 tags, 5 of which are includes.
   Unknown Includes:  4
   Unparsed Includes: 0
   Parsed Includes:   1

Include Path Summary:

  This file's project include search is handled by the EDE object:
    Buffer Target:  #<ede-compdb-target modules/audio_processing/gain_control_impl.cc>
    Buffer Project: #<ede-ninja-project webrtc>
    Backup in-project Locator: #<ede-locate-base Loc>
    EDE Project system include path: Empty

  This file's system include path is:
    /usr/include
    /usr/lib/gcc/x86_64-linux-gnu/4.8/include/
    /usr/local/include/
    /usr/lib/gcc/x86_64-linux-gnu/4.8/include-fixed/
    /usr/include/x86_64-linux-gnu/
    /usr/include/
    /usr/include/c++/4.8/
    /usr/include/x86_64-linux-gnu/c++/4.8/
    /usr/include/c++/4.8/backward/

Summary of all includes needed by gain_control_impl.cc
  gain_control_impl.cc :	6 tags, 5 are includes. 
  assert.h :	9 tags, 1 are includes. 
  features.h :	47 tags, 3 are includes. 
  stdc-predef.h :	0 tags, 0 are includes. 
  cdefs.h :	59 tags, 2 are includes. 
  stubs.h :	1 tags, 1 are includes. 
  wordsize.h :	3 tags, 0 are includes. 
  stubs-64.h :	14 tags, 0 are includes. 
```
And  ```M-: (oref ede-object compilation)``` returns ```nil```

**Comment by randomphrase** [comment]
Thanks again for the detailed bug report. This may be a separate issue to the original one, however.

A few things to check at when diagnosing ede-ninja-compdb problems:

1. Check the contents of your `*compdb:projname*` buffer. This contains the compilation database for the corresponding project, and it should be in JSON format. If the output is not strictly JSON formatted, then obviously it will not be parsed by ede-compdb. Hence look for spurious output, etc.

2. In general it is difficult to know what rule names to use when querying ninja. These are typically-generator specific and hence difficult to guess. I have included the standard "CXX_COMPILER" rules, which CMake emits, but you may have something different. In this case you will need to customize the `build-rules` slot, for example

```elisp
    (ede-add-project-to-global-list
     (ede-ninja-project 
      projname
      :file projfile
      :compdb-file compdb-file
      :build-command "ninja -j3"
      :build-rules '("icc14.0.3_cxx" "gcc4.8.3_cxx")
      )))))
```

You can typically look inside your ninja.build file and look for the `rule` statements. Find the ones which match your compiler(s) and add them to the `:build-rules` initializer.

If you can run `ninja -t compdb cxx_compiler` (where `cxx_compiler` is your build rule) and see the JSON output, then `ede-ninja-project` should be able to read it.

Let me know if this helps, I'll update the doco if so.

**Comment by zhongweiy** [comment]
Sorry for my late reply.

After adding build rules like following, it works like a charm:
```
(ede-add-project-to-global-list
 (ede-ninja-project "webrtc"
                     :file "~/webrtc/src/webrtc/webrtc.gyp"
                     :compdb-file "~/webrtc/src/out/Release/build.ninja"
                     :build-command "ninja"
                     :build-rules '("cxx" "cc" "cc_s")
                     ))
```
Thanks!
